name: Stress Action
runs-on: ubuntu-latest
inputs:
  test_type:
    description: Test type [pytest/maven]
    required: true
  extra_arguments:
    description: Extra arguments
    default: ''
  no_stress_runs:
    description: Number of no-stress runs
    default: '1'
  stress_runs:
    description: Number of stress runs
    default: '1'
runs:
  using: 'docker'
  image: 'Dockerfile'
